Traceback (most recent call last):
  File "/home/zimmer/neutrino_clustering_V2/simulation_numerical.py", line 1040, in <module>
    read_DM_halo_index(
  File "/home/zimmer/neutrino_clustering_V2/simulation_numerical.py", line 184, in read_DM_halo_index
    np.save(f'{out_dir}/DM_pos_{fname}.npy', DM_pos)
  File "<__array_function__ internals>", line 180, in save
  File "/home/zimmer/.conda/envs/neutrino_clustering/lib/python3.9/site-packages/numpy/lib/npyio.py", line 515, in save
    file_ctx = open(file, "wb")
FileNotFoundError: [Errno 2] No such file or directory: 'L025N752/DMONLY/SigmaConstant00/temp_data_PRRT/DM_pos_origID28_snap_0012.npy'
